# -*- coding: utf-8 -*-
"""2d to 3d image analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GI-FiBnZ3lD7Ux7PXCsKcPsRozedyZ3k
"""

from google.colab import drive
from PIL import Image

# Mount Google Drive
drive.mount('/content/drive')

# Path to the image on Google Drive
image_path = '/content/drive/MyDrive/image1.jpg'

# Load the image
image = Image.open(image_path)

# Display the image
image.show()

import cv2
import numpy as np
from PIL import Image


# Convert the image to a NumPy array
image_np = np.array(image)

# Convert the image to grayscale (black and white)
grayscale_image = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY)

# Binarize the image
_, binary_image = cv2.threshold(grayscale_image, 127, 255, cv2.THRESH_BINARY)

# Find contours
contours, _ = cv2.findContours(binary_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Draw the contours on the original image
image_with_contours = image_np.copy()
cv2.drawContours(image_with_contours, contours, -1, (0, 255, 0), 2)

# Display the image with contours
Image.fromarray(image_with_contours).show()

import matplotlib.pyplot as plt

# Get the color map of the image
color_map = plt.imshow(image)

# Show the color map
plt.axis('off')
plt.show()

import cv2
import numpy as np
from PIL import Image
from sklearn.preprocessing import MinMaxScaler
from skimage.feature import greycomatrix, greycoprops

# Load the image
image = Image.open('/content/drive/MyDrive/image1.jpg')

# Convert the image to a NumPy array
image_np = np.array(image)

# Convert the image to grayscale
gray_image = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY)

# Scale the image to the range [0, 1]
scaler = MinMaxScaler()
gray_image_scaled = scaler.fit_transform(gray_image.astype(float))

# Normalize the pixel values to the range [0, 255]
gray_image_normalized = (gray_image_scaled * 255).astype(np.uint8)

# Extract texture features (using the co-occurrence matrix)
glcm = greycomatrix(gray_image_normalized, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)
contrast = greycoprops(glcm, 'contrast')[0, 0]
dissimilarity = greycoprops(glcm, 'dissimilarity')[0, 0]
homogeneity = greycoprops(glcm, 'homogeneity')[0, 0]

# Print the texture features
print('Contrast:', contrast)
print('Dissimilarity:', dissimilarity)
print('Homogeneity:', homogeneity)

# Image segmentation (threshold segmentation)
_, binary_image = cv2.threshold(gray_image_normalized, 127, 255, cv2.THRESH_BINARY)

# Find contours
contours, _ = cv2.findContours(binary_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Draw the contours on the original image
image_with_contours = image_np.copy()
cv2.drawContours(image_with_contours, contours, -1, (0, 255, 0), 2)

# Display the image with contours
Image.fromarray(image_with_contours).show()

import cv2
import numpy as np
from PIL import Image
from sklearn.cluster import KMeans

# Load the image
image = Image.open('/content/drive/MyDrive/image1.jpg')

# Convert the image to a NumPy array
image_np = np.array(image)

# Convert the image to RGB
image_rgb = cv2.cvtColor(image_np, cv2.COLOR_BGR2RGB)

# Reshape the image into a one-dimensional array of pixels
pixels = image_rgb.reshape(-1, 3)

# K-Means clustering
k = 5  # Number of clusters
kmeans = KMeans(n_clusters=k, random_state=0)
labels = kmeans.fit_predict(pixels)

# Create a mask for each cluster
masks = []
for i in range(k):
    mask = np.zeros_like(labels, dtype=np.uint8)
    mask[labels == i] = 255
    masks.append(mask.reshape(image_rgb.shape[:2]))

# Apply the masks to the image
segmented_images = []
for i, mask in enumerate(masks):
    segmented_image = cv2.bitwise_and(image_rgb, image_rgb, mask=mask)
    segmented_images.append(segmented_image)

# Display the images with the highlighted clusters
for i, segmented_image in enumerate(segmented_images):
    # Print information about each image
    print(f"Segmented Image {i+1}")
    print(f"Cluster Label: {i}")
    print(f"Color: {kmeans.cluster_centers_[i]}")
    Image.fromarray(segmented_image).show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.cluster import KMeans

# Load the image
image = Image.open('/content/drive/MyDrive/image1.jpg')

# Convert the image to a NumPy array
image_np = np.array(image)

# Convert the image to RGB
image_rgb = cv2.cvtColor(image_np, cv2.COLOR_BGR2RGB)

# Reshape the image into a one-dimensional array of pixels
pixels = image_rgb.reshape(-1, 3)

# K-Means clustering
k = 5  # Number of clusters
kmeans = KMeans(n_clusters=k, random_state=0)
labels = kmeans.fit_predict(pixels)

# Create a mask for each cluster
masks = []
for i in range(k):
    mask = np.zeros_like(labels, dtype=np.uint8)
    mask[labels == i] = 255
    masks.append(mask.reshape(image_rgb.shape[:2]))

# Apply the masks to the image
segmented_images = []
for mask in masks:
    segmented_image = cv2.bitwise_and(image_rgb, image_rgb, mask=mask)
    segmented_images.append(segmented_image)

# Display the images with the highlighted clusters
for i, segmented_image in enumerate(segmented_images):
    plt.subplot(1, len(segmented_images), i+1)
    plt.imshow(segmented_image)
    plt.axis('off')

# Display each object separately
for i, segmented_image in enumerate(segmented_images):
    object_image = cv2.bitwise_and(image_np, image_np, mask=masks[i])
    Image.fromarray(object_image).show()

import cv2
import torch
import numpy as np
from PIL import Image
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from torchvision.transforms import functional as F
from google.colab import drive

drive.mount('/content/drive')

# Convert the masks to grayscale
gray_masks = [cv2.cvtColor(mask, cv2.COLOR_RGB2GRAY) for mask in segmented_images]

# Apply the Watershed algorithm to separate the objects
markers = np.zeros_like(gray_masks[0], dtype=np.int32)
for i, mask in enumerate(gray_masks):
    _, thresh = cv2.threshold(mask, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    sure_fg = cv2.erode(thresh, None, iterations=3)
    _, markers = cv2.connectedComponents(sure_fg)
    markers += 1
    markers[mask == 0] = 0

# Apply the Watershed algorithm to the original image
image_copy = image_np.copy()
cv2.watershed(image_copy, markers)
image_copy[markers == -1] = [255, 0, 0]  # Mark the object boundaries

# Save the segmented image
segmented_image_path = '/content/drive/MyDrive/segmented_image.jpg'
cv2.imwrite(segmented_image_path, image_rgb)

# Save the image with the marked object boundaries
image_with_boundaries_path = '/content/drive/MyDrive/image_with_boundaries.jpg'
cv2.imwrite(image_with_boundaries_path, image_copy)

# Display the segmented image
plt.imshow(image_rgb)
plt.title('Segmented Image')
plt.axis('off')
plt.show()

# Display the image with the marked object boundaries
plt.imshow(image_copy)
plt.title('Image with Boundaries')
plt.axis('off')
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.cluster import KMeans

# Load the image
image = Image.open('/content/drive/MyDrive/image1.jpg')

# Convert the image to a NumPy array
image_np = np.array(image)

# Convert the image to RGB
image_rgb = cv2.cvtColor(image_np, cv2.COLOR_BGR2RGB)

# Reshape the image into a one-dimensional array of pixels
pixels = image_rgb.reshape(-1, 3)

# K-Means clustering
k = 5  # Number of clusters
kmeans = KMeans(n_clusters=k, random_state=0)
labels = kmeans.fit_predict(pixels)

# Create a mask for each cluster
masks = []
for i in range(k):
    mask = np.zeros_like(labels, dtype=np.uint8)
    mask[labels == i] = 255
    masks.append(mask.reshape(image_rgb.shape[:2]))

# Apply the masks to the image
segmented_images = []
for mask in masks:
    segmented_image = cv2.bitwise_and(image_rgb, image_rgb, mask=mask)
    segmented_images.append(segmented_image)

# Convert the masks to grayscale
gray_masks = [cv2.cvtColor(mask, cv2.COLOR_RGB2GRAY) for mask in segmented_images]

# Apply the Watershed algorithm to separate the objects
markers = np.zeros_like(gray_masks[0], dtype=np.int32)
for i, mask in enumerate(gray_masks):
    _, thresh = cv2.threshold(mask, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    sure_fg = cv2.erode(thresh, None, iterations=3)
    _, markers = cv2.connectedComponents(sure_fg)
    markers += 1
    markers[mask == 0] = 0

# Apply the Watershed algorithm to the original image
image_copy = image_np.copy()
cv2.watershed(image_copy, markers)
image_copy[markers == -1] = [255, 0, 0]  # Mark the object boundaries

# Display each object separately
for i, mask in enumerate(masks):
    object_image = cv2.bitwise_and(image_rgb, image_rgb, mask=mask)
    object_image_resized = cv2.resize(object_image, (500, 500))  # Resize the image
    plt.subplot(1, len(masks), i+1)
    plt.imshow(object_image_resized)
    plt.axis('off')

plt.show()

area1 = 0  # Area of the previous object
for i, mask in enumerate(masks):
    object_image = cv2.bitwise_and(image_rgb, image_rgb, mask=mask)
    object_image_resized = cv2.resize(object_image, (500, 500))  # Resize the image

    # Compute the area of the object
    area = np.sum(mask) / 255

    # Estimate the distance based on the object's area
    distance = abs(area - area1)  # Example distance calculation

    # Add a text label to the image
    cv2.putText(object_image_resized, f'Distance: {distance:.2f}', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 0), 2)

    area1 = area  # Save the area of the current object

    plt.figure()
    plt.imshow(object_image_resized)
    plt.axis('off')
    plt.show()

import cv2
from PIL import Image
from google.colab.patches import cv2_imshow
# Find the darkest and the brightest pixel
min_intensity = np.min(gray_image)
max_intensity = np.max(gray_image)

# Find the coordinates of the darkest and the brightest pixel
min_coords = np.argwhere(gray_image == min_intensity)[0]
max_coords = np.argwhere(gray_image == max_intensity)[0]

# Mark the points on the image
marked_image = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)
marked_image = cv2.circle(marked_image, tuple(max_coords[::-1]), 5, (0, 0, 255), -1)  # Red dot for the brightest pixel
marked_image = cv2.circle(marked_image, tuple(min_coords[::-1]), 5, (0, 255, 0), -1)  # Green dot for the darkest pixel

# Display the image with the marked points
cv2_imshow(marked_image)

import cv2
import numpy as np
from PIL import Image
from google.colab.patches import cv2_imshow

# Load the image
image = Image.open('/content/drive/MyDrive/image2.png')

# Convert the image to a NumPy array
image_np = np.array(image)

# Convert the image to grayscale
gray_image = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY)

# Find the darkest and the brightest pixel
min_intensity = np.min(gray_image)
max_intensity = np.max(gray_image)

# Find the coordinates of the darkest and the brightest pixel
min_coords = np.argwhere(gray_image == min_intensity)[0]
max_coords = np.argwhere(gray_image == max_intensity)[0]

# Mark the points on the image
marked_image = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)
marked_image = cv2.circle(marked_image, tuple(max_coords[::-1]), 10, (0, 0, 255), -1)  # Red dot for the brightest pixel
marked_image = cv2.circle(marked_image, tuple(min_coords[::-1]), 10, (0, 255, 0), -1)  # Green dot for the darkest pixel

# Display the image with the marked points
cv2_imshow(marked_image)

import cv2
import torch
import urllib.request
import matplotlib.pyplot as plt
from PIL import Image
!pip install timm

model_type = "DPT_Large"     # MiDaS v3 - Large     (highest accuracy, slowest inference speed)
#model_type = "DPT_Hybrid"   # MiDaS v3 - Hybrid    (medium accuracy, medium inference speed)
#model_type = "MiDaS_small"  # MiDaS v2.1 - Small   (lowest accuracy, highest inference speed)

midas = torch.hub.load("intel-isl/MiDaS", model_type)

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
midas.to(device)
midas.eval()


midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")

if model_type == "DPT_Large" or model_type == "DPT_Hybrid":
    transform = midas_transforms.dpt_transform
else:
    transform = midas_transforms.small_transform



# Load the image
img = Image.open('/content/drive/MyDrive/image1.jpg')

# Convert the image to a NumPy array
img_array = np.array(img)
img_rgb = cv2.cvtColor(img_array, cv2.COLOR_BGR2RGB)

# Convert the image to a tensor and move it to the device
input_batch = transform(img_rgb).to(device)

with torch.no_grad():
    # Get the depth map prediction
    prediction = midas(input_batch)

    # Interpolate the prediction to obtain a depth map with the same dimensions as the original image
    prediction = torch.nn.functional.interpolate(
        prediction.unsqueeze(1),
        size=img_rgb.shape[:2],
        mode="bicubic",
        align_corners=False,
    ).squeeze()

output = prediction.cpu().numpy()

# Save the depth map
depth_map_path = '/content/drive/MyDrive/depth_map.jpg'
cv2.imwrite(depth_map_path, output)

# Visualize the depth map
plt.imshow(output)
plt.axis("off")
plt.show()

import cv2
import torch
import numpy as np
from PIL import Image
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from torchvision.transforms import functional as F

depth_map_path = '/content/drive/MyDrive/depth_map.jpg'
segmented_image_path = '/content/drive/MyDrive/segmented_image.jpg'

# Load the depth map and the segmented image
depth_map = np.array(Image.open(depth_map_path))
segmented_image = np.array(Image.open(segmented_image_path))

# Visualize the depth map
plt.imshow(depth_map)
plt.axis('off')
plt.show()

# Visualize the segmented image
plt.imshow(segmented_image)
plt.axis('off')
plt.show()

# Build the 3D scene from the depth map and the segmented image
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Get the coordinates of pixels with non-zero depth values
nonzero_indices = np.nonzero(depth_map)
x = nonzero_indices[1]
y = nonzero_indices[0]
z = depth_map[nonzero_indices]

# Get the object colors from the segmented image
colors = segmented_image[nonzero_indices]

# Plot the points in 3D space
ax.scatter(x, -y, z, c=colors / 255.0, s=1)  # Flip the direction of the Y axis

# Configure the axes
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Depth')

# Flip the direction of the X and Z axes
ax.invert_xaxis()
ax.invert_zaxis()

# Show the 3D scene
plt.show()

!pip install mplcursors
!pip install pythreejs
!pip install plotly

import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import mplcursors

depth_map_path = '/content/drive/MyDrive/depth_map.jpg'
segmented_image_path = '/content/drive/MyDrive/segmented_image.jpg'

# Load depth map and segmented image
depth_map = np.array(Image.open(depth_map_path))
segmented_image = np.array(Image.open(segmented_image_path))

# Create 3D plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Get nonzero indices from depth map
nonzero_indices = np.nonzero(depth_map)
x = nonzero_indices[1]
y = -nonzero_indices[0]  # Invert y-axis to match image coordinates
z = depth_map[nonzero_indices]

# Get colors from segmented image
colors = segmented_image[nonzero_indices] / 255.0

# Scatter plot of 3D points
ax.scatter(x, y, z, c=colors, s=1)

# Configure axes labels and limits
ax.set_xlabel('X')
ax.set_zlabel('Y')
ax.set_ylabel('Depth')

ax.set_xlim(0, depth_map.shape[1])
ax.set_ylim(-depth_map.shape[0], 0)
ax.set_zlim(np.min(z), np.max(z))



# Configure cursor hover
cursors = mplcursors.cursor(hover=True)
cursors.connect('add', lambda sel: sel.annotation.set_text(f'Color: {sel.artist.get_facecolor()}'))

# Show 3D plot
plt.show()

import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import mplcursors

# Paths to the images
depth_map_path = '/content/drive/MyDrive/depth_map.jpg'
segmented_image_path = '/content/drive/MyDrive/segmented_image.jpg'

# Load the images
depth_map = np.array(Image.open(depth_map_path))
segmented_image = np.array(Image.open(segmented_image_path))

# Create the figure
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Get the non-zero indices from the depth map
nonzero_indices = np.nonzero(depth_map)
x = nonzero_indices[1]
y = -nonzero_indices[0]  # Invert the y-axis to match the image coordinates
z = depth_map[nonzero_indices]

# Take the colors from the segmented image
colors = segmented_image[nonzero_indices] / 255.0

# Create the scatter plot
ax.scatter(x, y, z, c=colors, s=1)

# Configure the axis labels
ax.set_xlabel('X')
ax.set_zlabel('Y')
ax.set_ylabel('Depth')

ax.set_xlim(0, depth_map.shape[1])
ax.set_ylim(-depth_map.shape[0], 0)
ax.set_zlim(np.min(z), np.max(z))

# Enable interactive mode
ax.mouse_init()  # Enable rotation with the mouse

# Configure the cursor
cursors = mplcursors.cursor(hover=True)
cursors.connect('add', lambda sel: sel.annotation.set_text(f'Color: {sel.artist.get_facecolor()}'))

# Show the interactive window
plt.show()
