# -*- coding: utf-8 -*-
"""generation_scene

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liRCdg3iIdnpKxUOkfi1qQHV89jDyWTB
"""

import matplotlib
from matplotlib import pyplot as plt
from PIL import Image
import torch
from transformers import GLPNImageProcessor, GLPNForDepthEstimation

feature_extractor = GLPNImageProcessor.from_pretrained("vinvino02/glpn-nyu")
model = GLPNForDepthEstimation.from_pretrained("vinvino02/glpn-nyu")

image = Image.open("model.jpg")
new_height = 480 if image.height > 480 else image.height
new_height -= (new_height % 32)
new_width = int(new_height * image.width / image.height)
diff = new_width % 32

new_width = new_width - diff if diff < 16 else new_width + 32 - diff
new_size = (new_width, new_height)
image = image.resize(new_size)

from PIL import Image
import numpy as np
import torch

# Ensure the image is a PIL Image
if isinstance(image, np.ndarray):
    image = Image.fromarray(image)
elif torch.is_tensor(image):
    image = Image.fromarray(image.numpy())

if image.mode != "RGB":
    image = image.convert("RGB")

# Use the feature extractor
inputs = feature_extractor(images=image, return_tensors="pt")

inputs = feature_extractor(images=image, return_tensors="pt")

with torch.no_grad():
  outputs = model(**inputs)
  predicted_depth = outputs.predicted_depth

pad = 16
output =predicted_depth.squeeze().cpu().numpy()*1000.0
output = output[pad:-pad, pad:-pad]
image = image.crop((pad,pad, image.width - pad, image.height - pad))


fig, ax = plt.subplots(1,2)
ax[0].imshow(image)
ax[0].tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)
ax[1].imshow(output, cmap='plasma')
ax[1].tick_params(left=False, bottom=False, labelleft=False, labelbottom = False)
plt.tight_layout()
plt.pause(5)

!pip install open3d

import numpy as np
import open3d as o3d

width, height = image.size

depth_image = (output*255 / np.max(output)).astype('uint8')
image = np.array(image)

depth_o3d = o3d.geometry.Image(depth_image)
image_o3d = o3d.geometry.Image(image)
rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(image_o3d, depth_o3d, convert_rgb_to_intensity=False)

camera_intrinsic = o3d.camera.PinholeCameraIntrinsic()
camera_intrinsic.set_intrinsics(width, height, 500, 500, width/2, height/2)

pcd_raw = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_image, camera_intrinsic)
points = np.asarray(pcd_raw.points)
colors = np.asarray(pcd_raw.colors)

fig = plt.figure(figsize=(10, 7))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(points[:, 0], points[:, 1], points[:, 2], c=colors, s=1)
plt.show()

o3d.io.write_point_cloud("point.ply", pcd_raw)

# Commented out IPython magic to ensure Python compatibility.
# %pip install plotly

import numpy as np
import plotly.graph_objects as go

points = np.asarray(pcd_raw.points)
colors = (np.asarray(pcd_raw.colors) * 255).astype(np.uint8)

colors_hex = ['rgb({},{},{})'.format(r, g, b) for r, g, b in colors]

fig = go.Figure(data=[go.Scatter3d(
    x=points[:, 0],
    y=points[:, 1],
    z=points[:, 2],
    mode='markers',
    marker=dict(size=1, color=colors_hex)
)])

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Z"
    ),
    title="Interactive 3D point cloud plot"
)

fig.show()

DATANAME ="point_filtered (1).ply"
pcd_f = o3d.io.read_point_cloud(DATANAME)
import numpy as np
import plotly.graph_objects as go

points = np.asarray(pcd_f.points)
colors = (np.asarray(pcd_f.colors) * 255).astype(np.uint8)

colors_hex = ['rgb({},{},{})'.format(r, g, b) for r, g, b in colors]

fig = go.Figure(data=[go.Scatter3d(
    x=points[:, 0],
    y=points[:, 1],
    z=points[:, 2],
    mode='markers',
    marker=dict(size=1, color=colors_hex)
)])

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Z"
    )
)

fig.show()

cl, ind = pcd_raw.remove_statistical_outlier(nb_neighbors=20, std_ratio=20.0)
pcd = pcd_raw.select_by_index(ind)

pcd.estimate_normals()
pcd.orient_normals_to_align_with_direction()

mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth=10, n_threads=1)[0]

rotation = mesh.get_rotation_matrix_from_xyz((np.pi, 0, 0))
mesh.rotate(rotation, center=(0,0,0))

import plotly.graph_objects as go

rotation = mesh.get_rotation_matrix_from_xyz((np.pi, 0, 0))
mesh.rotate(rotation, center=(0, 0, 0))

vertices = np.asarray(mesh.vertices)
triangles = np.asarray(mesh.triangles)

x = vertices[:, 0]
y = vertices[:, 1]
z = vertices[:, 2]

i = triangles[:, 0]
j = triangles[:, 1]
k = triangles[:, 2]

vertex_colors = np.asarray(mesh.vertex_colors)
colors = vertex_colors[:, :3]

triangle_colors = (colors[i] + colors[j] + colors[k]) / 3

fig = go.Figure(data=[go.Mesh3d(
    x=x,
    y=y,
    z=z,
    i=i,
    j=j,
    k=k,
    intensity=triangle_colors[:, 0],
    colorscale='Viridis',
    opacity=0.7
)])

fig.update_layout(
    scene=dict(
        xaxis=dict(showgrid=False),
        yaxis=dict(showgrid=False),
        zaxis=dict(showgrid=False),
    ),
    title="3D Mesh with Color"
)

fig.show()

o3d.io.write_triangle_mesh("3dmesh.obj", mesh)

!pip install transformers

import cv2
import numpy as np

# Load the image

from PIL import Image

#!gdown 14CSVdok0NTd9NRHKv2WXg34Z7Wykui8A
image_file = '/content/room_test.jpg'
image_ = Image.open(image_file)
new_height = 480 if image_.height > 480 else image_.height
new_height -= (new_height % 32)
new_width = int(new_height * image_.width / image_.height)
diff = new_width % 32

new_width = new_width - diff if diff < 16 else new_width + 32 - diff
new_size = (new_width, new_height)
image_ = image_.resize(new_size)

image_.save('output.jpg')  # Save in JPEG format


# Load the image
image = cv2.imread("output.jpg")

new_height = 480 if image.height > 480 else image.height
new_height -= (new_height % 32)
new_width = int(new_height * image.width / image.height)
diff = new_width % 32

new_width = new_width - diff if diff < 16 else new_width + 32 - diff
new_size = (new_width, new_height)
image = image.resize(new_size)
mask = np.zeros(image.shape[:2], np.uint8)

# Define the initial rectangle
rect = (50, 50, image.shape[1] - 100, image.shape[0] - 100)

# Arrays for the GrabCut algorithm
bgd_model = np.zeros((1, 65), np.float64)
fgd_model = np.zeros((1, 65), np.float64)

# Apply GrabCut
cv2.grabCut(image, mask, rect, bgd_model, fgd_model, 5, cv2.GC_INIT_WITH_RECT)

# Create the final mask
mask2 = np.where((mask == 2) | (mask == 0), 0, 1).astype('uint8')
foreground = image * mask2[:, :, np.newaxis]

# Save the result
cv2.imwrite("foreground.png", foreground)

import cv2
import numpy as np
from PIL import Image

# Load and resize the image using Pillow
image_file = '/content/room_test.jpg'
image_ = Image.open(image_file)
new_height = 480 if image_.height > 480 else image_.height
new_height -= (new_height % 32)
new_width = int(new_height * image_.width / image_.height)
diff = new_width % 32
new_width = new_width - diff if diff < 16 else new_width + 32 - diff
new_size = (new_width, new_height)
image_ = image_.resize(new_size)
image_.save('output.jpg')  # Save in JPEG format

# Load the image using OpenCV
image = cv2.imread("output.jpg")

# Use shape to get the image dimensions
height, width = image.shape[:2]
new_height = 480 if height > 480 else height
new_height -= (new_height % 32)
new_width = int(new_height * width / height)
diff = new_width % 32
new_width = new_width - diff if diff < 16 else new_width + 32 - diff
new_size = (new_width, new_height)

# Resize the image using OpenCV
image = cv2.resize(image, (new_width, new_height))

# Create the mask for GrabCut
mask = np.zeros(image.shape[:2], np.uint8)

# Define the initial rectangle
rect = (50, 50, image.shape[1] - 100, image.shape[0] - 100)

# Arrays for the GrabCut algorithm
bgd_model = np.zeros((1, 65), np.float64)
fgd_model = np.zeros((1, 65), np.float64)

# Apply GrabCut
cv2.grabCut(image, mask, rect, bgd_model, fgd_model, 5, cv2.GC_INIT_WITH_RECT)

# Create the final mask
mask2 = np.where((mask == 2) | (mask == 0), 0, 1).astype('uint8')
foreground = image * mask2[:, :, np.newaxis]

# Save the result
cv2.imwrite("foreground.png", foreground)

!pip install easygui

!pip install pillow rembg

!pip install onnxruntime

from rembg import remove
from PIL import Image
from io import BytesIO
input = Image.open('test.jpg')
output = remove(input)
output.save('foreground.png')

!pip install open3d

import numpy as np
import open3d as o3d
import matplotlib.pyplot as plt

DATANAME ="point.ply"
pcd = o3d.io.read_point_cloud(DATANAME)

pcd_center = pcd.get_center()
pcd.translate(-pcd_center)

nn = 16
std_multiplier = 10
filtered_pcd = pcd.remove_statistical_outlier(nn, std_multiplier)

outliers = pcd.select_by_index(filtered_pcd[1], invert = True)
outliers.paint_uniform_color([1,0,0])
filtered_pcd = filtered_pcd[0]

o3d.io.write_point_cloud("point_filtered.ply", filtered_pcd)

voxel_size = 0.0000021

pcd_downsampled = filtered_pcd.voxel_down_sample(voxel_size = voxel_size)

nn_distance = np.mean(pcd.compute_nearest_neighbor_distance())

nn_distance

radius_normals = nn_distance*4

pcd_downsampled.estimate_normals(search_param = o3d.geometry.KDTreeSearchParamHybrid(radius=radius_normals, max_nn=16), fast_normal_computation=True)


pcd_downsampled.paint_uniform_color([0.6, 0.6, 0.6])
o3d.io.write_point_cloud("point_downsampled.ply", pcd_downsampled)

front = {0.96, 0.26, -0.03}
lookat = {0.008, -0.2, -0.48}
up={0.011, 0.095, 0.99}
zoom = 0.25

pt_to_plane_dist = 0.0001

plane_model, inliers = pcd.segment_plane(distance_threshold=pt_to_plane_dist, ransac_n=3, num_iterations =1000)

[a,b,c,d] = plane_model

inlier_cloud = pcd.select_by_index(inliers)
inlier_cloud.paint_uniform_color([1.0, 0, 0])
outlier_cloud = pcd.select_by_index(inliers, invert=True)
outlier_cloud.paint_uniform_color([0.6,0.6,0.6])

max_plane_idx = 6
pt_to_plane_dist =0.06

segment_models ={}
segments = {}
rest = pcd

for i in range(max_plane_idx):
  colors = plt.get_cmap('tab20')(i)
  segment_models[i], inliers = rest.segment_plane(distance_threshold=pt_to_plane_dist, ransac_n=3,num_iterations=10000)
  segments[i]=rest.select_by_index(inliers)
  segments[i].paint_uniform_color(list(colors[:3]))
  print("pass",i,"/", max_plane_idx, "done.")

o3d.io.write_point_cloud("output.ply", rest)  # Save the remaining points
for i in range(max_plane_idx):
    o3d.io.write_point_cloud(f"segment_{i}.ply", segments[i])  # Save the segments

import matplotlib.pyplot as plt
import numpy as np

# Convert the segments into numpy arrays for visualization
all_points = []
colors = []
for i in range(max_plane_idx):
    points = np.asarray(segments[i].points)
    color = np.tile(np.random.rand(3), (points.shape[0], 1))
    all_points.append(points)
    colors.append(color)

# Merge all the segments
all_points = np.vstack(all_points)
colors = np.vstack(colors)

# Display the points
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(all_points[:, 0], all_points[:, 1], all_points[:, 2], c=colors, s=1)
plt.show()

labels = np.array(rest.cluster_dbscan(eps=0.05, min_points = 5))

max_label = labels.max()
print(f"point cloud has {max_label +1} clusters")

colors = plt.get_cmap("tab10")(labels / (max_label if max_label > 0 else 1))
colors[labels < 0] = 0
rest.colors = o3d.utility.Vector3dVector(colors[:, :3])

o3d.visualisation.draw_geometries([segments[i] for i in range(max_plane_idx)]+[rest], zoom=zoom, front=front, lookat=lookat, up=up)

!pip install ultralytics

from ultralytics import YOLO
import cv2
from matplotlib import pyplot as plt

# Load a pretrained segmentation model
model = YOLO("yolov8n-seg.pt")  # Use YOLOv8 with the smallest model (nano) for speed

# Load the image
image_path = 'model.jpg'  # Replace with the path to your image
image = cv2.imread(image_path)

# Apply segmentation
results = model(image, task="segment")

# Get the segmentation masks
result_masks = results[0].masks.data.cpu().numpy()

# Visualize the result
annotated_image = results[0].plot()  # Get the annotated image
plt.imshow(cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()

output_path = "segmented_image.jpg"
cv2.imwrite(output_path, annotated_image)
print(f"Result saved to {output_path}")

import cv2
import numpy as np
from PIL import Image, ImageEnhance
import matplotlib.pyplot as plt
import torch

# Path to the image
image_path = "model.jpg"

# === 1. LOADING AND PREPROCESSING ===
def preprocess_image_for_depth(img_pil):
    img = np.array(img_pil)

    # Convert to LAB and apply CLAHE to the L channel
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    l_clahe = clahe.apply(l)
    lab_clahe = cv2.merge((l_clahe, a, b))
    img_clahe = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2RGB)

    # Apply a bilateral filter to remove noise while preserving edges
    img_filtered = cv2.bilateralFilter(img_clahe, d=9, sigmaColor=75, sigmaSpace=75)

    return Image.fromarray(img_filtered)

# === 2. DEPTH MAP GENERATION ===
def get_depth_map(image_pil):
    image_resized = image_pil.resize(new_size)
    inputs = feature_extractor(images=image_resized, return_tensors="pt")
    with torch.no_grad():
        outputs = model(**inputs)
    depth = outputs.predicted_depth.squeeze().cpu().numpy()

    # Normalize and smooth the depth map
    depth = (depth - np.min(depth)) / (np.max(depth) - np.min(depth))  # [0,1]
    depth = cv2.GaussianBlur(depth, (5, 5), 0)
    return depth[pad:-pad, pad:-pad]

# === 3. RUN ===
image_raw = Image.open(image_path).convert("RGB")
image_proc = preprocess_image_for_depth(image_raw)

depth_raw = get_depth_map(image_raw)
depth_proc = get_depth_map(image_proc)

# === 4. VISUALIZATION ===
fig, axs = plt.subplots(2, 2, figsize=(12, 6))

axs[0, 0].imshow(image_raw)
axs[0, 0].set_title("Original")
axs[0, 1].imshow(image_proc)
axs[0, 1].set_title("After preprocessing")

axs[1, 0].imshow(depth_raw, cmap='plasma')
axs[1, 0].set_title("Depth without preprocessing")
axs[1, 1].imshow(depth_proc, cmap='plasma')
axs[1, 1].set_title("Depth after preprocessing")

for ax in axs.flat:
    ax.axis('off')
plt.tight_layout()
plt.show()

import os
import cv2
import numpy as np
import torch
from PIL import Image
import matplotlib.pyplot as plt

# List of possible files
image_files = [
    "model.jpg",
    "segmented_image.jpg",
    "test.jpg",
    "foreground.png",
    "output.jpg",
    "room_test.jpg"
]

# Check availability
available_images = [f for f in image_files if os.path.isfile(f)]
print("Available images:", available_images)

# Configure the resize parameters
def get_new_size(image):
    new_height = 480 if image.height > 480 else image.height
    new_height -= (new_height % 32)
    new_width = int(new_height * image.width / image.height)
    diff = new_width % 32
    new_width = new_width - diff if diff < 16 else new_width + 32 - diff
    return (new_width, new_height)

# Image preprocessing (CLAHE + filtering)
def preprocess_image(image_pil):
    img = np.array(image_pil)
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    l_clahe = clahe.apply(l)
    lab_clahe = cv2.merge((l_clahe, a, b))
    img_clahe = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2RGB)
    img_filtered = cv2.bilateralFilter(img_clahe, d=9, sigmaColor=75, sigmaSpace=75)
    return Image.fromarray(img_filtered)

# Depth map
def get_depth_map(image_pil, new_size):
    image_resized = image_pil.resize(new_size)
    inputs = feature_extractor(images=image_resized, return_tensors="pt")
    with torch.no_grad():
        outputs = model(**inputs)
    depth = outputs.predicted_depth.squeeze().cpu().numpy()
    depth = (depth - np.min(depth)) / (np.max(depth) - np.min(depth))  # normalization
    depth = cv2.GaussianBlur(depth, (5, 5), 0)
    return depth

# Main loop
for img_path in available_images:
    try:
        image_raw = Image.open(img_path).convert("RGB")
        new_size = get_new_size(image_raw)
        pad = 16

        image_proc = preprocess_image(image_raw)

        depth_raw = get_depth_map(image_raw, new_size)[pad:-pad, pad:-pad]
        depth_proc = get_depth_map(image_proc, new_size)[pad:-pad, pad:-pad]

        # Visualization
        fig, axs = plt.subplots(2, 2, figsize=(12, 6))
        axs[0, 0].imshow(image_raw)
        axs[0, 0].set_title(f"{img_path} — original")
        axs[0, 1].imshow(image_proc)
        axs[0, 1].set_title("After preprocessing")
        axs[1, 0].imshow(depth_raw, cmap='plasma')
        axs[1, 0].set_title("Depth (without processing)")
        axs[1, 1].imshow(depth_proc, cmap='plasma')
        axs[1, 1].set_title("Depth (with preprocessing)")
        for ax in axs.flat:
            ax.axis('off')
        plt.tight_layout()
        plt.show()

    except Exception as e:
        print(f"Error processing {img_path}: {e}")

import os
import cv2
import numpy as np
import torch
from PIL import Image
import matplotlib.pyplot as plt

# ======= PREPROCESSING FLAGS (ON / OFF) =======
USE_CLAHE = True
USE_EDGE_OVERLAY = True
USE_MORPH_FILTERS = True
USE_UNSHARP_MASK = True

# ======= FILES TO PROCESS =======
image_files = [
    "model.jpg",
    "segmented_image.jpg",
    "test.jpg",
    "foreground.png",
    "output.jpg",
    "room_test.jpg"
]
available_images = [f for f in image_files if os.path.isfile(f)]
print("Available images:", available_images)

# ======= HELPER FUNCTIONS =======
def get_new_size(image):
    new_height = 480 if image.height > 480 else image.height
    new_height -= (new_height % 32)
    new_width = int(new_height * image.width / image.height)
    diff = new_width % 32
    new_width = new_width - diff if diff < 16 else new_width + 32 - diff
    return (new_width, new_height)

def apply_edge_overlay(image_pil):
    image = np.array(image_pil)
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    edges = cv2.Canny(gray, 100, 200)
    edges_colored = cv2.cvtColor(edges, cv2.COLOR_GRAY2RGB)
    result = cv2.addWeighted(image, 0.9, edges_colored, 0.3, 0)
    return Image.fromarray(result)

def apply_morphological_boost(image_pil):
    img_gray = cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2GRAY)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (15, 15))
    top_hat = cv2.morphologyEx(img_gray, cv2.MORPH_TOPHAT, kernel)
    black_hat = cv2.morphologyEx(img_gray, cv2.MORPH_BLACKHAT, kernel)
    boosted = cv2.add(cv2.subtract(cv2.add(img_gray, top_hat), black_hat), 0)
    return Image.fromarray(cv2.cvtColor(boosted, cv2.COLOR_GRAY2RGB))

def apply_unsharp_mask(image_pil):
    image = np.array(image_pil)
    blurred = cv2.GaussianBlur(image, (9, 9), 10)
    sharpened = cv2.addWeighted(image, 1.5, blurred, -0.5, 0)
    return Image.fromarray(sharpened)

def preprocess_image(image_pil):
    img = np.array(image_pil)

    # contour analysis
    if USE_CLAHE:
        lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
        l, a, b = cv2.split(lab)
        clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
        l_clahe = clahe.apply(l)
        lab_clahe = cv2.merge((l_clahe, a, b))
        img = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2RGB)

        # Bilateral filtering
        img = cv2.bilateralFilter(img, d=9, sigmaColor=75, sigmaSpace=75)

    img_pil = Image.fromarray(img)

    if USE_MORPH_FILTERS:
        img_pil = apply_morphological_boost(img_pil)
    if USE_EDGE_OVERLAY:
        img_pil = apply_edge_overlay(img_pil)
    if USE_UNSHARP_MASK:
        img_pil = apply_unsharp_mask(img_pil)

    return img_pil

def get_depth_map(image_pil, new_size):
    image_resized = image_pil.resize(new_size)
    inputs = feature_extractor(images=image_resized, return_tensors="pt")
    with torch.no_grad():
        outputs = model(**inputs)
    depth = outputs.predicted_depth.squeeze().cpu().numpy()
    depth = (depth - np.min(depth)) / (np.max(depth) - np.min(depth))  # normalization
    depth = cv2.GaussianBlur(depth, (5, 5), 0)
    return depth

# ======= MAIN PROCESSING LOOP =======
for img_path in available_images:
    try:
        image_raw = Image.open(img_path).convert("RGB")
        new_size = get_new_size(image_raw)
        pad = 16

        image_proc = preprocess_image(image_raw)

        depth_raw = get_depth_map(image_raw, new_size)[pad:-pad, pad:-pad]
        depth_proc = get_depth_map(image_proc, new_size)[pad:-pad, pad:-pad]

        # Visualization
        fig, axs = plt.subplots(2, 2, figsize=(12, 6))
        axs[0, 0].imshow(image_raw)
        axs[0, 0].set_title(f"{img_path} — original")
        axs[0, 1].imshow(image_proc)
        axs[0, 1].set_title("After preprocessing")
        axs[1, 0].imshow(depth_raw, cmap='plasma')
        axs[1, 0].set_title("Depth (without processing)")
        axs[1, 1].imshow(depth_proc, cmap='plasma')
        axs[1, 1].set_title("Depth (with preprocessing)")
        for ax in axs.flat:
            ax.axis('off')
        plt.tight_layout()
        plt.show()

    except Exception as e:
        print(f"Error processing {img_path}: {e}")

from skimage.metrics import structural_similarity as ssim

def compare_depth_maps(depth1, depth2):
    mae = np.mean(np.abs(depth1 - depth2))
    rmse = np.sqrt(np.mean((depth1 - depth2) ** 2))
    ssim_index = ssim(depth1, depth2, data_range=1.0)
    return mae, rmse, ssim_index

# Modified part of the main loop
results = []

for img_path in available_images:
    try:
        image_raw = Image.open(img_path).convert("RGB")
        new_size = get_new_size(image_raw)
        pad = 16

        image_proc = preprocess_image(image_raw)

        depth_raw = get_depth_map(image_raw, new_size)[pad:-pad, pad:-pad]
        depth_proc = get_depth_map(image_proc, new_size)[pad:-pad, pad:-pad]

        mae, rmse, ssim_index = compare_depth_maps(depth_raw, depth_proc)
        results.append((img_path, mae, rmse, ssim_index))

        # Visualization
        fig, axs = plt.subplots(2, 2, figsize=(12, 6))
        axs[0, 0].imshow(image_raw)
        axs[0, 0].set_title(f"{img_path} — original")
        axs[0, 1].imshow(image_proc)
        axs[0, 1].set_title("After preprocessing")
        axs[1, 0].imshow(depth_raw, cmap='plasma')
        axs[1, 0].set_title("Depth (without processing)")
        axs[1, 1].imshow(depth_proc, cmap='plasma')
        axs[1, 1].set_title("Depth (with preprocessing)")
        for ax in axs.flat:
            ax.axis('off')
        plt.tight_layout()
        plt.show()

    except Exception as e:
        print(f"Error processing {img_path}: {e}")

# Tabular output of the results
import pandas as pd
df = pd.DataFrame(results, columns=["Image", "MAE", "RMSE", "SSIM"])
print("\nComparison of depth map changes:")
print(df.to_markdown(index=False))

import cv2
import numpy as np
from matplotlib import pyplot as plt

# Load the image in grayscale
image_path = "figure.png"
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

# Split into 3 equal parts by width
h, w = image.shape
w_cut = w // 3
slices = [image[:, i*w_cut:(i+1)*w_cut] for i in range(3)]

# Find the minimum dimensions among the slices
min_h = min(s.shape[0] for s in slices)
min_w = min(s.shape[1] for s in slices)

# Resize all parts to the minimum size
resized = [cv2.resize(s, (min_w, min_h), interpolation=cv2.INTER_AREA) for s in slices]

# Normalize the values to the range [0, 1]
norm_slices = [cv2.normalize(s.astype('float32'), None, 0, 1, cv2.NORM_MINMAX) for s in resized]

# Sum and average
summed = np.mean(norm_slices, axis=0)

# Convert to uint8
summed_uint8 = (summed * 255).astype(np.uint8)

# CLAHE to increase local contrast
clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
clahe_result = clahe.apply(summed_uint8)

# Unsharp mask
blurred = cv2.GaussianBlur(clahe_result, (5, 5), 0)
sharpened = cv2.addWeighted(clahe_result, 1.5, blurred, -0.5, 0)

# Visualization
plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(image, cmap='plasma')
plt.title('Original')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(clahe_result, cmap='plasma')
plt.title('Contour analysis')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(sharpened, cmap='plasma')
plt.title('Final (enhancement)')
plt.axis('off')

plt.tight_layout()
plt.show()
